apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  labels:
    app: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - name: application
          image: piyush7248/complaint:1
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: 800Mi
              cpu: 150m
---
apiVersion: v1
kind: Service
metadata:
  name: application
spec:
  selector:
    app: application
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000 